# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telnumber', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contacts_description', models.TextField()),
                ('facebook_link', models.CharField(max_length=255)),
                ('twitter_link', models.CharField(max_length=255)),
                ('instagram_link', models.CharField(max_length=255)),
            ],
        ),
    ]
