# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='short_content',
            field=models.TextField(default=1, max_length=511),
            preserve_default=False,
        ),
    ]
